feat(ProcessMonitor): add linux os process memory logging
oramake/oramake-framework pull request #23
Opened 2022-12-02 11:07 UTC by DEN4IK2115

2022-12-14 14:47 UTC, elysyonok requested changes

2022-12-15 06:44 UTC, DEN4IK2115 commented on Module/ProcessMonitor/DB/pkg_ProcessMonitor.pkb
> +  function getProcessMemoryLinux
Спасибо!

2022-12-15 06:45 UTC, DEN4IK2115 commented on Module/ProcessMonitor/DB/pkg_ProcessMonitor.pkb
> +  end;
Добавил обработку ошибок и название после end

2022-12-15 06:45 UTC, DEN4IK2115 commented on Module/ProcessMonitor/DB/pkg_ProcessMonitor.pkb
> +      getProcessMemory( oracleOsPid => oracleOsPid)
Убрал лишний пробел

2022-12-15 06:47 UTC, DEN4IK2115 commented on Module/ProcessMonitor/DB/Doc/version.txt
> +[+] ��������� ����������� ������� ������, ���������� ��������� ���� Oracle
На данный момент нашел только информацию о том, что такое происходит с файлами в кодировке 1251. Нашел несколько инструкций о том, как это можно попробовать исправить. Попробую их применить в своем репозитории и если получится, то отпишусь о том как это можно сделать

2022-12-15 16:59 UTC, elysyonok commented on Module/ProcessMonitor/DB/Doc/version.txt
> +[+] ��������� ����������� ������� ������, ���������� ��������� ���� Oracle
Было бы очень здорово для всех!!!

2022-12-15 17:00 UTC, elysyonok commented
Отличная работа!

2022-12-15 17:01 UTC, elysyonok approved these changes

2022-12-16 06:26 UTC, merged