[ST-1283]
oramake/oramake-framework pull request #24
Opened 2022-12-09 12:05 UTC by AVP75

Tag: 1.4.0 ( 2022-12-09)
[+] Добавление пакета <pkg_DataSizeCompression> со следующими методами:
- getTableListPipe - выборка таблиц с Lob полями для оценки необходимости сжатия;
- sendEmail - отправка сообщений на почту с информацией из getTableListPipe;
- ShrinkLobSegment - запуск заданий на сжатие Lob-сегментов на основании данных из getTableListPipe.

2022-12-12 12:14 UTC, elysyonok requested changes

2022-12-12 12:14 UTC, elysyonok commented on Module/DataSize/DB/pkg_DataSizeCompression.pkb
> +  inOwner        varchar2   default 'OUTOFSTAFF,ICA'
Все параметры по-умолчанию должны быть null по стандартам

2022-12-12 12:14 UTC, elysyonok commented on Module/DataSize/DB/pkg_DataSizeCompression.pkb
> +  tableName       - ������ ������ ����� �������, ALL - ��� ������� (default 'OOS_DOCUMENT,OOS_AGENT,OOS_COMPARE_ACT,OOS_ACT_DOC_SCAN,ICA_REQUEST_FILE')
специфики таблиц быть не должно

2022-12-12 12:14 UTC, elysyonok commented on Module/DataSize/DB/pkg_DataSizeCompression.pkb
> +  for c in (
предлагаю осмысленное название переменной

2022-12-12 12:14 UTC, elysyonok commented on Module/DataSize/DB/pkg_DataSizeCompression.pkb
> +  logger1 lg_logger_t := lg_logger_t.GetLogger(
лог должен быть общим для пакета (см. другие пакеты)

2022-12-12 12:14 UTC, elysyonok commented on Module/DataSize/DB/pkg_DataSizeCompression.pkb
> +  tableName       - ������ ������ ����� �������, ALL - ��� ������� (default 'OOS_DOCUMENT,OOS_AGENT,OOS_COMPARE_ACT,OOS_ACT_DOC_SCAN,ICA_REQUEST_FILE')
строчки должны быть меньше 80 символов длины

2022-12-12 12:14 UTC, elysyonok commented on Module/DataSize/DB/pkg_DataSizeCompression.pkb
> +  logger1.Debug(
debug с маленькой буквы

2022-12-12 12:14 UTC, elysyonok commented on Module/DataSize/DB/pkg_DataSizeCompression.pkb
> +procedure ShrinkLobSegment (
функции начинаются с маленькой буквы

2022-12-13 13:42 UTC, AVP75 commented on Module/DataSize/DB/pkg_DataSizeCompression.pkb
> +  inOwner        varchar2   default 'OUTOFSTAFF,ICA'
Поправил

2022-12-13 13:42 UTC, AVP75 commented on Module/DataSize/DB/pkg_DataSizeCompression.pkb
> +  for c in (
Поправил

2022-12-13 13:42 UTC, AVP75 commented on Module/DataSize/DB/pkg_DataSizeCompression.pkb
> +  tableName       - ������ ������ ����� �������, ALL - ��� ������� (default 'OOS_DOCUMENT,OOS_AGENT,OOS_COMPARE_ACT,OOS_ACT_DOC_SCAN,ICA_REQUEST_FILE')
Поправил

2022-12-13 13:42 UTC, AVP75 commented on Module/DataSize/DB/pkg_DataSizeCompression.pkb
> +  logger1.Debug(
Поправил

2022-12-13 13:43 UTC, AVP75 commented on Module/DataSize/DB/pkg_DataSizeCompression.pkb
> +procedure ShrinkLobSegment (
Поправил

2022-12-15 16:57 UTC, elysyonok requested changes

2022-12-15 16:57 UTC, elysyonok commented on Module/DataSize/DB/Install/Batch/Last/DataSizeCompressionReport/process.job.sql
> +  pkg_operator.login('ServerSezam');
не нужно логиниться так - батч сам логинится

2022-12-15 16:57 UTC, elysyonok commented on Module/DataSize/DB/Install/Batch/Last/DataSizeCompressionReport/process.job.sql
> +    , tableSize => 1000000000 -- 1 ��
Думаю должны быть параметры а не магические числа

2022-12-15 16:57 UTC, elysyonok commented on Module/DataSize/DB/Install/Config/1.4.0/after-action.sql
> +@oms-activate-batch.sql DataSizeCompressionReport
отлично

2022-12-15 16:57 UTC, elysyonok commented on Module/DataSize/DB/Install/Config/1.4.0/define.mk
> +  Install/Batch/Last/DataSizeFragmentation/* \
отлично

2022-12-15 16:57 UTC, elysyonok commented on Module/DataSize/DB/pkg_DataSizeCompression.pkb
> +  logger lg_logger_t := lg_logger_t.GetLogger(
хорошо

2022-12-16 09:51 UTC, AVP75 commented on Module/DataSize/DB/Install/Batch/Last/DataSizeCompressionReport/process.job.sql
> +  pkg_operator.login('ServerSezam');
удалил логин

2022-12-16 09:52 UTC, AVP75 commented on Module/DataSize/DB/Install/Batch/Last/DataSizeCompressionReport/process.job.sql
> +    , tableSize => 1000000000 -- 1 ��
добавил параметры

2022-12-19 17:29 UTC, elysyonok approved these changes
Спасибо, @AVP75 !

2022-12-19 17:30 UTC, merged